build with docker in docker:
  stage: build
  image: docker:27.2.0
  services:
    - docker:27.2.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"

  tags:
    - docker-in-docker
  script:
    - "apt-get update && apt-get upgrade -y && apt-get install -y build-essential cmake gcc g++"
    - "cmake ."
    - "make"

