on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    - steps:
      - uses: actions/checkout@v3

      - run: "apt-get update && apt-get upgrade -y && apt-get install -y build-essential cmake gcc g++"
      - run: "cmake ."
      - run: "make"
      
      - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: entscheidungsfinder